name: 'Log in to registries'
description: 'Log in to GitHub Container Registry and Docker Hub'

inputs:
  dockerhub-username:
    description: 'Docker Hub username'
    required: true
  dockerhub-token:
    description: 'Docker Hub access token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Log in to GitHub Container Registry (ghcr.io)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }}
