name: Sync Docker Hub Description

on:
  push:
    branches:
      - master
    paths:   # Trigger on changes to relevant files
      - README.md
      - .github/workflows/sync-dockerhub-description.yaml
    tags:   # Trigger when tags are created. Match format like v1.2.3 (semantic versioning).
      - 'v*.*.*'
  release:   # Trigger when a new release is published
    types:
      - published
  schedule:   # Auto-trigger on 1st of each month at 00:00 UTC
    - cron: '0 0 1 * *'
  workflow_dispatch:   # Manual trigger

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
      - name: Check event source
        run: |
          echo "Triggered by: ${{ github.event_name }}"

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Update Docker Hub README
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/network-helper
          short-description: ${{ github.event.repository.description }}
          readme-filepath: ./README.md
